### ISSUE TITLE
Music: check for is_rest is buggy

### ISSUE THREAD

**Issue by tlively** [cs50/checks#21]
This code passes the test, but it should not:
```
bool is_rest(string s)
{
    int rest = strcmp(s, "\0"); // BUG: comparison with wrong string!
    if (rest == 0)
    {
        return true;
    }
    else
    {
        return false;
    }
}
```

**Comment by dmalan** [comment]
Hm, looks like we're not currently compiling with `-Werror and -Wall`. Cf. https://github.com/cs50/checks/blob/master/cs50/2017/fall/music/check50/__init__.py#L23-L28. @crossroads1112, @brianyu28, is that deliberate? 

Else, given the `"\0"`, `clang` whould have outputted:

```
error: format string contains '\0' within the string body [-Werror,-Wformat]
```

Even so, comparing `s` with `"\0"` is effectively the same in this case as comparing it with `\""`, @tlively, no? In both cases, you're comparing `s` against a string of length zero; it just so happens that `"\0"` comprises two bytes and `""` one?

**Comment by tlively** [comment]
@dmalan Good point. I didn't even register that it was valid to have a null terminator escape in a string literal, but of course it is.
