### ISSUE TITLE
why does check50 speller for edX require questions.txt?

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/checks#29]
Not sure when this was changed, but you cannot run `check50` for speller unless you have the `questions.txt` file.  Probably not a big deal as most students would have that file, and it's required for submission.

**Comment by dmalan** [comment]
Interesting corner case. A side effect of `check50` v2. We'll discuss if/how to fix!

**Comment by curiouskiwi** [comment]
obsolete now
