### ISSUE TITLE
Clang flags don't include std=c11 which can cause student code to not compile

### ISSUE THREAD

**Issue by curiouskiwi** [cs50/checks#5]
Our default make runs:
`clang -ggdb3 -O0 -Qunused-arguments -std=c11 -Wall -Werror    vigenere.c  -lcrypt -lcs50 -lm -o vigenere`  as an example for vigenere.

But check50 uses:
`clang -o vigenere vigenere.c -lcs50 -lm`

Not including the `-std=c11` can cause a file that has a variable called `index` to not compile, because `index` is also a variable name that is declared in the `string.h` header.

In the example I have, the code includes a *global* variable called `int index;`

    ~/workspace/ $ clang -o vigenere vigenere.c -lcs50 -lm
     vigenere.c:5:5: error: redefinition of 'index' as different kind of symbol
      int index, j = 0;
          ^
     /usr/include/string.h:489:14: note: previous definition is here
     extern char *index (const char *__s, int __c)
                  ^

But compiles fine with the c11 flag.

Can we use the same clang flags in our checks?

**Comment by brianyu28** [comment]
Yeah this should be a pretty easy change to make, just updating the `spawn` commands in the checks. @crossroads1112, any problems I'm not anticipating that we might run into if we do this?

**Comment by cmlsharp** [comment]
No, we should definitely make this change (probably to the rest of the checks as well).

**Comment by dmalan** [comment]
@crossroads1112 able to make the tweaks this eve?

**Comment by cmlsharp** [comment]
Sorry, I missed this notification! I will make them tonight!
